let a=45;
let b=45;

try{
    console.log(a*b+def);

}
catch(e){
    console.log("Error occured... ");  
}
finally{
    console.log("Finally block is executed.");
}